[language-server.clangd]
command = "clangd"
args = [
  "--query-driver=/nix/store/*/bin/gcc,/nix/store/*/bin/cc,/nix/store/*/bin/clang,/nix/store/*/bin/clang++,/nix/store/*/bin/g++,/nix/store/*/bin/c++"
]
